"""
Django settings for pruebaServ project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0y_$d6#0eoizi_am9hav*-xnhu_6r$mlp+5vqvl1tul!l128z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.100.29', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',  # <--- AGREGA ESTA LÍNEA (Obligatoria para el login)
    'drf_spectacular',
    'miApp',
]
# Agrega esto para que Django sepa que TÚ mandas con el modelo de Usuario
AUTH_USER_MODEL = 'miApp.Usuario'
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <--- Esta debe ser la primera
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # 'django.middleware.csrf.CsrfViewMiddleware',  # <--- CORRECCIÓN: PONLE ESTE # AL PRINCIPIO
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'pruebaServ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pruebaServ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'prueba',
        'USER': 'Leonardo',
        'PASSWORD': 'Leonardo123',
        'HOST': 'prueba',  # Este es el nombre del servicio en tu docker-compose
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-bo'  # Para que los meses salgan en español

TIME_ZONE = 'America/La_Paz'  # Configura la zona horaria de Bolivia

USE_I18N = True

USE_TZ = True  # Deja esto en True para que Django maneje internamente los cambios

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
CORS_ALLOW_ALL_ORIGINS = True # Para desarrollo es lo más cómodo

# Configuración de Django REST Framework para usar Spectacular
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # <--- ESTO ES VITAL
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
# Configuración visual de la documentación
SPECTACULAR_SETTINGS = {
    'TITLE': 'API Identificación de Colores - Leonardo',
    'DESCRIPTION': 'Documentación de endpoints para el Product Owner y Frontend (UPC Grupo 3)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Esto ayuda a que el Swagger se vea más limpio
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}
import os

# La URL que verás en el navegador (ej: localhost:8000/media/...)
MEDIA_URL = '/media/'

# La carpeta real en tu computadora/docker donde se guardan las fotos
# Busca esta línea y cámbiala por esta:
MEDIA_ROOT = BASE_DIR / 'media'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

