# Generated by Django 6.0.4 on 2026-04-27 22:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(help_text='Ej: #FF5733', max_length=7, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo (ej: Azul Cobalto)', max_length=50, null=True)),
                ('r', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('g', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('b', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('rgb_code', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Biblioteca Maestra de Colores',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='miApp.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='capturas/')),
                ('colores_hex', models.JSONField(blank=True, default=list)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
                'ordering': ['-fecha_captura'],
            },
        ),
        migrations.CreateModel(
            name='ComposicionPaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(default=0, help_text='Qué tanto brilla este color en esta paleta específicamente')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.color')),
            ],
            options={
                'verbose_name': 'Composición de Paleta',
                'verbose_name_plural': 'Composiciones de Paletas',
                'ordering': ['-porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Combinación', max_length=100)),
                ('origen', models.CharField(choices=[('CAMARA', 'Captura de Cámara'), ('MANUAL', 'Creación/Combinación Manual'), ('EDICION', 'Edición de Existente')], default='MANUAL', help_text='Indica si la paleta nació de una foto o del combinador manual', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('captura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paletas_generadas', to='miApp.captura')),
                ('colores', models.ManyToManyField(blank=True, related_name='paletas_contenidas', through='miApp.ComposicionPaleta', to='miApp.color')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paletas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paleta',
                'verbose_name_plural': 'Paletas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='composicionpaleta',
            name='paleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.paleta'),
        ),
        migrations.AddConstraint(
            model_name='captura',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('nombre', 'usuario'), name='unique_nombre_captura_por_usuario'),
        ),
    ]
