# Generated by Django 6.0.4 on 2026-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionpaleta',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
    ]
